[workspace]
resolver = "2"
members = [
    "proxy-server",
    "proxy-client",
    "proxy-agent",
    "protocol",
    "timeout-stream",
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
